#!/usr/bin/env bash
# Factorization Challenge

calculate_factors() {
    num=$1
    factors=$(factor "$num" | cut -d ':' -f 2-)
    echo "$num = $factors"
}

if [ $# -ne 1 ]; then
    echo 'Usage: script_name <file>'
    exit 1
else
    input_file="$1"

    if [ ! -f "$input_file" ]; then
        echo "File not found: $input_file"
        exit 1
    fi

    while read -r number; do
        calculate_factors "$number"
    done < "$input_file"
fi
