#!/usr/bin/env bash

# Function to check if a number is a factor of another number
factor_check() {
    if [ $# -ne 3 ]; then
        arguments=("$@")
        index=0
        factor_product=1

        for arg in "${arguments[@]}"; do
            if [ $index -gt 1 ]; then
                factor_product=$(echo "$arg*$factor_product" | bc)
            fi
            index=$((index + 1))
        done
    else
        factor_product=$3
    fi

    num1=$2
    num_as_string=$(echo "$1" | tr ':' '=')

    result=$(echo "if($factor_product > $num1) 1 else 0" | bc)
    if ((result == 1)); then
        temp_num=$num1
        num1=$factor_product
        factor_product=$temp_num
    }

    echo "$num_as_string$num1*$factor_product"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factor_checker <file>'
    exit 1
else
    while read line
    do
        factorization=$(factor "$line")
        factor_check $factorization
    done < "$1"
fi

