#!/usr/bin/env bash

# Function to check if a number is a factor of another number
check_factor()
{
    if [ $# -ne 3 ];
    then
        arguments=("$@")
        count=0
        num2=1
        for arg in "${arguments[@]}";
        do
            if [ $count -gt 1 ];
            then
                num2=$(echo "$arg*$num2" | bc)
            fi
            count=$((count + 1))
        done
    else
        num2=$3
    fi

    num1=$2
    formatted_num=$(echo "$1" | tr ':' '=')

    result=$(echo "if($num2 > $num1) 1 else 0" | bc)
    if ((result == 1)); then
        temp_num=$num1
        num1=$num2
        num2=$temp_num
    fi

    echo "$formatted_num$num1*$num2"
}

if [ $# -ne 1 ]
then
    echo 'Usage: factor_checker <file>'
    exit 1
else
    while read input
    do
        result=$(factor "$input")
        check_factor $result
    done < "$1"
fi

