#!/usr/bin/env bash

is_prime() {
    number=$1
    if [ $number -le 1 ]; then
        return 1
    fi

    for ((i = 2; i * i <= number; i++)); do
        if [ $((number % i)) -eq 0 ]; then
            return 1
        fi
    done

    return 0
}

find_prime_factors() {
    n=$1
    for ((p = 2; p <= n / 2; p++)); do
        if is_prime "$p"; then
            q=$((n / p))
            if [ $((p * q)) -eq $n ] && is_prime "$q"; then
                echo "$n=$p*$q"
                return
            fi
        fi
    done

    echo "No prime factors found for $n"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r n; do
        find_prime_factors "$n"
    done < "$1"
fi

